### ISSUE TITLE
Déployer la configuration avant de redémarrer le service

### ISSUE THREAD

**Issue by BastienBalaud** [clusson/ansible#2]
Dans le fichier : https://github.com/clusson/ansible/blob/master/roles/php/tasks/configure.yml
Tu déploies la configuration de la pool php fpm après avoir redémarré le service et donc la configuration n'est pas prise en compte lors du redémarrage.

**Comment by sylvainDNS** [comment]
Fixed in https://github.com/clusson/ansible/commit/ece0acb80e86b16ac749b80d46b0623fb35bd57b

Thanks for collab ( ͝° ͜ʖ͡°)
